---
name: practical-09
break: true
indent: 4
---

src/main/java/practicalten:
    GridGame.java:
        ConfirmFileExists
        CountSingleLineComments --language Java --count 6
        MatchFileFragment --fragment "{Your Name Here}" --count 0 --exact
        MatchFileFragment --fragment "TODO" --count 0 --exact
        MatchFileFragment --fragment ".getGrid()" --count 1 --exact
        MatchFileFragment --fragment "for (" --count 2 --exact
        MatchFileFragment --fragment "int[][]" --count 1 --exact
        MatchFileFragment --fragment "new Grid(" --count 1
        MatchFileFragment --fragment "if (" --count 1

ExecuteCommand --command "gradle build"
ExecuteCommand --command "gradle -q --console plain gradeRun"
CountCommandOutput --command "gradle -q --console plain gradeRun" --count 4